# Github action for automatically adding label or setting assignee when a new
# Issue or PR is opened. https://github.com/marketplace/actions/issue-labeler

name: ðŸ·ï¸ã€€Label(Title and Body)
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
          variable_name: BOT_TOKEN
      - uses: Naturalclar/issue-action@v2.0.1
        with:
          github-token: ${{ env.BOT_TOKEN }}
          title-or-body: title
          parameters: >
            [
              {
                "keywords": ["bug","fix"],
                "labels": ["PR: fix"]
              },
              {
                "keywords": ["chore"],
                "labels": ["PR: chore"]
              },
              {
                "keywords": ["feat","feature","enhancement","enhance"],
                "labels": ["PR: feature"]
              },
              {
                "keywords": ["docs","documentation","document"],
                "labels": ["PR: documentation"]
              },
              {
                "keywords": ["refactor"],
                "labels": ["PR: refactor"]
              },
              {
                "keywords": ["dependency","dep","deps"],
                "labels": ["PR: dependency"]
              }
            ]
