name: ğŸ‘‹ã€€Welcome
on:
  pull_request_target:
    types: [opened, closed]
  issues:
    types: [opened]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          GITHUB_TOKEN: ${{ secrets.LIBRO_TOKEN }}
          FIRST_ISSUE: |
            ğŸ‘‹ @{{ author }}

            Thanks for opening your first issue here! If you're reporting a ğŸ bug, please make sure you include steps to reproduce it.
            To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/difizen/libro/blob/main/CONTRIBUTING.md).
            We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.

          FIRST_PR: |
            ğŸ‘‹ @{{ author }}

            ğŸ’– Thanks for opening this pull request! ğŸ’–

            Please follow the [contributing guidelines](https://github.com/difizen/libro/blob/main/CONTRIBUTING.md). And we use [semantic commit messages to streamline the release process.

            Examples of commit messages with semantic prefixes:
            - `fix(ai-native): fix cursor in chat`
            - `feat(lab): support for julia script editing and preview`
            - `docs: add sql cell manual`

            Things that will help get your PR across the finish line:
            - Follow the TypeScript, JavaScript, CSS and React coding style.
            - Run `npm run lint` locally to catch formatting errors earlier.
            - Document any user-facing changes you've made.
            - Include tests when adding/changing behavior.
            - Include screenshots and animated GIFs whenever possible.

            Please be patient and we will get back to you as soon as we can.

          FIRST_PR_MERGED: |
            ğŸ‘‹ @{{ author }}

            Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
